<a href="https://colab.research.google.com/github/DENGCPU/TensorFlow-Study/blob/main/1%E9%A2%84%E5%A4%87%E7%9F%A5%E8%AF%86--pandas%E6%95%B0%E6%8D%AE%E5%A4%84%E7%90%86.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
value = 'apple' if 2>1 else 'watermelon'
print(value)

apple


In [37]:
# 匿名函数
[(lambda x: 2*x)(x) for x in range(5)]

[0, 2, 4, 6, 8]

In [38]:
list(map(lambda x: 2*x, range(5)))

[0, 2, 4, 6, 8]

In [39]:
list(map(lambda x, y: str(x)+'_'+y, range(5), list('abcde')))

['0_a', '1_b', '2_c', '3_d', '4_e']

In [40]:
L1,L2,L3 = list('abc'), list('def'), list('hij')
list(zip(L1,L2,L3))

[('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j')]

In [41]:
tuple(zip(L1,L2,L3))

(('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j'))

In [42]:
for i,j,k in zip(L1,L2,L3):
  print(i,j,k)

a d h
b e i
c f j


In [43]:
L = list("abcd")

for index, value in enumerate(L):
  print(index,value)

0 a
1 b
2 c
3 d


In [44]:
# 对两个列表建立字典映射
dict(zip(L1,L2))

{'a': 'd', 'b': 'e', 'c': 'f'}

In [45]:
# 使用*和zip进行解压
zipped =  list(zip(L1,L2,L3))
zipped

[('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j')]

In [46]:
list(zip(*zipped))

[('a', 'b', 'c'), ('d', 'e', 'f'), ('h', 'i', 'j')]

In [47]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [48]:
# 等差数列
np.linspace(1,5,10) #起始，终止（包含），样本个数

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [49]:
np.arange(1,5,2) #起始，终止（不包含）、步长

array([1, 3])

In [50]:
# 特殊矩阵
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
np.eye(3)  # 3*3单位矩阵

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
np.eye(3,k=1)  #偏移对角线1个单位的伪单位矩阵

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [53]:
np.full((2,3),10) #元祖传入大小，10是填充数字

array([[10, 10, 10],
       [10, 10, 10]])

In [54]:
np.full((2,3),[1,2,3]) #每行传入相同的列表

array([[1, 2, 3],
       [1, 2, 3]])

In [55]:
# 随机矩阵
np.random.rand(3) #0-1均匀分布的三个随机数

array([0.71518937, 0.60276338, 0.54488318])

In [56]:
np.random.rand(2,3)

array([[0.4236548 , 0.64589411, 0.43758721],
       [0.891773  , 0.96366276, 0.38344152]])

In [57]:
#生成（a,b)区间的均匀分布
a,b = 5, 15
(b-a)*np.random.rand(3) +a

array([12.91725038, 10.2889492 , 10.68044561])

In [58]:
# 或者使用库函数
np.random.uniform(5,15,3)

array([14.25596638,  5.71036058,  5.871293  ])

In [59]:
# randn生成正态分布
np.random.randn(3)

array([0.44386323, 0.33367433, 1.49407907])

In [60]:
np.random.randn(2,2)

array([[-0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982]])

In [61]:
sigma, mu = 2.5, 3
mu + np.random.randn(3)*sigma

array([4.63404649, 5.1610905 , 1.14458745])

In [62]:
# 使用工具函数生成一元正态分布
np.random.normal(3,2.5,3)

array([ 8.67438656, -0.63591419,  3.11439629])

In [63]:
# randint 随机整数数组
low, high, size =  5,15, (2,3)
np.random.randint(low,high,size) #不包含最大值

array([[11, 13,  9],
       [ 6,  9, 14]])

In [64]:
#np.random.choice() 以一定概率抽样，默认为有放回抽样
my_list = ['a', 'b', 'c','d']
np.random.choice(my_list,2,replace=False,p=[0.1,0.7,0.1,0.1])

array(['b', 'd'], dtype='<U1')

In [65]:
np.random.choice(my_list,(2,3))

array([['d', 'b', 'b'],
       ['d', 'c', 'd']], dtype='<U1')

In [66]:
np.random.seed(0) #固定随机数生成结果
np.random.rand()

0.5488135039273248

In [67]:
np.random.seed(0)
np.random.rand()

0.5488135039273248

In [68]:
# 数组的转置
np.zeros((2,3)).T

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [69]:
# 数组的合并 r_上下合并
np.r_[np.zeros((2,3)),np.zeros((2,3))]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [70]:
#c_左右合并
np.c_[np.zeros((2,3)),np.zeros((2,3))]

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [71]:
# 一维数组和二维数组合并应该看作是列向量, 长度一致时只有左右合并，不能上下合并
try:
  np.r_[np.array([0,0]),np.zeros((2,1))]
except Exception as e:
  Err_Msg = e

Err_Msg

ValueError('all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)')

In [72]:
np.c_[np.array([0,0]),np.zeros((2,3))]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])